### ISSUE TITLE
WPA3 probably not workgin

### ISSUE THREAD

**Issue by mklomp** [mirte-robot/mirte-install-scripts#15]
On the MDP image that we created internally we ran into the issue that the wifi-connect is not working as soon as there is a WPA3 network floating around.  This seems to be an [issue with wifi-connect](https://github.com/balena-os/wifi-connect/issues/416). We need to check to what extend we are facing this issue as well.

**Comment by ArendJan** [comment]
- Connecting to any other network when there is a WPA3 in the air works with the latest image. 
- Connecting to the WPA3 network is not yet possible, will give a ```Error: Connection activation failed: (53) The Wi-Fi network could not be found.``` error.
